// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvvzgeqzutmdcfinesxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dnpnZXF6dXRtZGNmaW5lc3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDM1ODksImV4cCI6MjA2NTQxOTU4OX0.6YDre1oy-OwuR6fDtcq8sjqrkTFVZhmOqim7wjNnf7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);